cmake_minimum_required(VERSION 3.20)
# Keep module dependencies explicit as the codebase grows.
set(domain_allowed domain)
set(platform_allowed platform)
set(json_allowed json domain platform)
set(application_allowed application domain json platform)
set(infrastructure_allowed infrastructure domain json platform)
set(ui_allowed ui domain application infrastructure json platform)
set(app_allowed app ui infrastructure)

foreach(layer domain platform json application infrastructure ui app)
  file(GLOB_RECURSE sources "${SOURCE_ROOT}/src/${layer}/*.h" "${SOURCE_ROOT}/src/${layer}/*.cpp")
  foreach(source IN LISTS sources)
    file(STRINGS "${source}" includes REGEX "^#include")
    foreach(line IN LISTS includes)
      if(line MATCHES "^#include \"([^\"]+)\"")
        set(header "${CMAKE_MATCH_1}")
        if(layer STREQUAL "ui" AND header STREQUAL "resources.h")
          continue()
        endif()
        if(NOT header MATCHES "^([^/]+)/")
          message(FATAL_ERROR "Use module-qualified includes: ${source}: ${line}")
        endif()
        set(dependency "${CMAKE_MATCH_1}")
        if(NOT dependency IN_LIST ${layer}_allowed)
          message(FATAL_ERROR "Forbidden dependency ${layer} -> ${dependency}: ${source}")
        endif()
      endif()
      if(layer STREQUAL "domain" AND line MATCHES "(windows|winhttp|commctrl|shlobj|objbase)\\.h")
        message(FATAL_ERROR "Domain must remain independent of Windows: ${source}")
      endif()
    endforeach()
  endforeach()
endforeach()
message(STATUS "Architecture dependencies passed")
